#!/bin/bash

#PBS -m abe
#PBS -M mhibbins@iu.edu
#PBS -l walltime=10:00:00,vmem=16GB,nodes=1:ppn=1
#PBS -N phylonet_s9_analysis_41
#PBS -e /N/dc2/scratch/mhibbins/outputs
#PBS -o /N/dc2/scratch/mhibbins/outputs
cd /N/dc2/scratch/mhibbins/introgression_review_sims/
java -jar PhyloNet/jar/PhyloNet_3.8.2.jar network_method_scripts/phylonet_s9_5taxa/phylonet_s9_5taxa_41.nexus > network_method_results/phylonet_s9_5taxa_results/phylonet_s9_5taxa_results_41.txt

